import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# Map locations
BEDROOM_MAP_NUM = 355
MOM_MAP_NUM = 408
PALLET_TOWN_MAP_NUM = 3204
OAK_LAB_MAP_NUM = 3210
ROUTE_1_MAP_NUM = 3010
VIRIDIAN_POKE_CENTER_MAP_NUM = 4281
VIRIDIAN_CITY_MAP_NUM = 414
VIRIDIAN_MART_MAP_NUM = 408  # why is this the same as my house??
ROUTE_2_MAP_NUM = 473
