import os

SCRIPT_DIR = os.path.dirname(os.path.abspath(__file__))

# Map locations
BEGINNING_MENU_MAP_NUM = 0
BEDROOM_MAP_NUM = 1
OAK_LAB_MAP_NUM = 4

# Decoding strings in Pokemon:
def decode(bytes):
    return ""


# Dynamic-RAM-related helpers:
def offset(addr, byHowManyAsHex):
    if byHowManyAsHex == 0:
        return addr

    newAddr = addr + int(byHowManyAsHex, 16)
    return newAddr


# Dynamic RAM address map-related offset functions
def X_POS_SHIFT(addr):
    return offset(addr, "0")


def Y_POS_SHIFT(addr):
    return offset(addr, "2")


def CURRENT_MAP(addr):
    return offset(addr, "4")


def CURRENT_MAP_BANK(addr):
    return offset(addr, "5")


# Dynamic RAM address trainer-related offset functions
def CHARACTER_NAME(addr):
    return offset(addr, "0")


def GENDER(addr):
    return offset(addr, "8")


def TRAINER_ID(addr):
    return offset(addr, "A")


def SECRET_ID(addr):
    return offset(addr, "C")


def OPTIONS(addr):
    return offset(addr, "14")


# Pokemon substructure-related offset functions
# Growth
def SPECIES(addr):
    return offset(addr, "0")


def ITEM_HELD(addr):
    return offset(addr, "2")


def EXPERIENCE(addr):
    return offset(addr, "4")


def PP_BONUSES(addr):
    return offset(addr, "8")


def FRIENDSHIP(addr):
    return offset(addr, "9")


def UNKNOWN(addr):
    return offset(addr, "A")


# Attacks
def MOVE_1(addr):
    return offset(addr, "0")


def MOVE_2(addr):
    return offset(addr, "2")


def MOVE_3(addr):
    return offset(addr, "4")


def MOVE_4(addr):
    return offset(addr, "6")


def PP_1(addr):
    return offset(addr, "8")


def PP_2(addr):
    return offset(addr, "9")


def PP_3(addr):
    return offset(addr, "A")


def PP_4(addr):
    return offset(addr, "B")


# The rest of this file is an in-memory datastore of all the moves in the game
movesByNumber = {
    1: {
        "Num": 1,
        "Name": "Pound",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 35,
        "Power": 40,
        "Accuracy": "100%",
    },
    2: {
        "Num": 2,
        "Name": "Karate Chop",
        "Type": "Fighting",
        "Category": "Physical",
        "PP": 25,
        "Power": 50,
        "Accuracy": "100%",
    },
    3: {
        "Num": 3,
        "Name": "Double Slap",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 10,
        "Power": 15,
        "Accuracy": "85%",
    },
    4: {
        "Num": 4,
        "Name": "Comet Punch",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 15,
        "Power": 18,
        "Accuracy": "85%",
    },
    5: {
        "Num": 5,
        "Name": "Mega Punch",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 20,
        "Power": 80,
        "Accuracy": "85%",
    },
    6: {
        "Num": 6,
        "Name": "Pay Day",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 20,
        "Power": 40,
        "Accuracy": "100%",
    },
    7: {
        "Num": 7,
        "Name": "Fire Punch",
        "Type": "Fire",
        "Category": "Physical",
        "PP": 15,
        "Power": 75,
        "Accuracy": "100%",
    },
    8: {
        "Num": 8,
        "Name": "Ice Punch",
        "Type": "Ice",
        "Category": "Physical",
        "PP": 15,
        "Power": 75,
        "Accuracy": "100%",
    },
    9: {
        "Num": 9,
        "Name": "Thunder Punch",
        "Type": "Electric",
        "Category": "Physical",
        "PP": 15,
        "Power": 75,
        "Accuracy": "100%",
    },
    10: {
        "Num": 10,
        "Name": "Scratch",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 35,
        "Power": 40,
        "Accuracy": "100%",
    },
    11: {
        "Num": 11,
        "Name": "Vise Grip",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 30,
        "Power": 55,
        "Accuracy": "100%",
    },
    12: {
        "Num": 12,
        "Name": "Guillotine",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 5,
        "Power": "—",
        "Accuracy": "30%",
    },
    13: {
        "Num": 13,
        "Name": "Razor Wind",
        "Type": "Normal",
        "Category": "Special",
        "PP": 10,
        "Power": 80,
        "Accuracy": "100%",
    },
    14: {
        "Num": 14,
        "Name": "Swords Dance",
        "Type": "Normal",
        "Category": "Status",
        "PP": 30,
        "Power": "—",
        "Accuracy": "—",
    },
    15: {
        "Num": 15,
        "Name": "Cut",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 30,
        "Power": 50,
        "Accuracy": "95%",
    },
    16: {
        "Num": 16,
        "Name": "Gust",
        "Type": "Flying",
        "Category": "Special",
        "PP": 35,
        "Power": 40,
        "Accuracy": "100%",
    },
    17: {
        "Num": 17,
        "Name": "Wing Attack",
        "Type": "Flying",
        "Category": "Physical",
        "PP": 35,
        "Power": 60,
        "Accuracy": "100%",
    },
    18: {
        "Num": 18,
        "Name": "Whirlwind",
        "Type": "Normal",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "100%",
    },
    19: {
        "Num": 19,
        "Name": "Fly",
        "Type": "Flying",
        "Category": "Physical",
        "PP": 15,
        "Power": 70,
        "Accuracy": "95%",
    },
    20: {
        "Num": 20,
        "Name": "Bind",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 20,
        "Power": 15,
        "Accuracy": "75%",
    },
    21: {
        "Num": 21,
        "Name": "Slam",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 20,
        "Power": 80,
        "Accuracy": "75%",
    },
    22: {
        "Num": 22,
        "Name": "Vine Whip",
        "Type": "Grass",
        "Category": "Physical",
        "PP": 10,
        "Power": 35,
        "Accuracy": "100%",
    },
    23: {
        "Num": 23,
        "Name": "Stomp",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 20,
        "Power": 65,
        "Accuracy": "100%",
    },
    24: {
        "Num": 24,
        "Name": "Double Kick",
        "Type": "Fighting",
        "Category": "Physical",
        "PP": 30,
        "Power": 30,
        "Accuracy": "100%",
    },
    25: {
        "Num": 25,
        "Name": "Mega Kick",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 5,
        "Power": 120,
        "Accuracy": "75%",
    },
    26: {
        "Num": 26,
        "Name": "Jump Kick",
        "Type": "Fighting",
        "Category": "Physical",
        "PP": 25,
        "Power": 70,
        "Accuracy": "95%",
    },
    27: {
        "Num": 27,
        "Name": "Rolling Kick",
        "Type": "Fighting",
        "Category": "Physical",
        "PP": 15,
        "Power": 60,
        "Accuracy": "85%",
    },
    28: {
        "Num": 28,
        "Name": "Sand Attack",
        "Type": "Ground",
        "Category": "Status",
        "PP": 15,
        "Power": "—",
        "Accuracy": "100%",
    },
    29: {
        "Num": 29,
        "Name": "Headbutt",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 15,
        "Power": 70,
        "Accuracy": "100%",
    },
    30: {
        "Num": 30,
        "Name": "Horn Attack",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 25,
        "Power": 65,
        "Accuracy": "100%",
    },
    31: {
        "Num": 31,
        "Name": "Fury Attack",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 20,
        "Power": 15,
        "Accuracy": "85%",
    },
    32: {
        "Num": 32,
        "Name": "Horn Drill",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 5,
        "Power": "—",
        "Accuracy": "30%",
    },
    33: {
        "Num": 33,
        "Name": "Tackle",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 35,
        "Power": 35,
        "Accuracy": "95%",
    },
    34: {
        "Num": 34,
        "Name": "Body Slam",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 15,
        "Power": 85,
        "Accuracy": "100%",
    },
    35: {
        "Num": 35,
        "Name": "Wrap",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 20,
        "Power": 15,
        "Accuracy": "85%",
    },
    36: {
        "Num": 36,
        "Name": "Take Down",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 20,
        "Power": 90,
        "Accuracy": "85%",
    },
    37: {
        "Num": 37,
        "Name": "Thrash",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 20,
        "Power": 90,
        "Accuracy": "100%",
    },
    38: {
        "Num": 38,
        "Name": "Double-Edge",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 15,
        "Power": 120,
        "Accuracy": "100%",
    },
    39: {
        "Num": 39,
        "Name": "Tail Whip",
        "Type": "Normal",
        "Category": "Status",
        "PP": 30,
        "Power": "—",
        "Accuracy": "100%",
    },
    40: {
        "Num": 40,
        "Name": "Poison Sting",
        "Type": "Poison",
        "Category": "Physical",
        "PP": 35,
        "Power": 15,
        "Accuracy": "100%",
    },
    41: {
        "Num": 41,
        "Name": "Twineedle",
        "Type": "Bug",
        "Category": "Physical",
        "PP": 20,
        "Power": 25,
        "Accuracy": "100%",
    },
    42: {
        "Num": 42,
        "Name": "Pin Missile",
        "Type": "Bug",
        "Category": "Physical",
        "PP": 20,
        "Power": 14,
        "Accuracy": "85%",
    },
    43: {
        "Num": 43,
        "Name": "Leer",
        "Type": "Normal",
        "Category": "Status",
        "PP": 30,
        "Power": "—",
        "Accuracy": "100%",
    },
    44: {
        "Num": 44,
        "Name": "Bite",
        "Type": "Dark",
        "Category": "Physical",
        "PP": 25,
        "Power": 60,
        "Accuracy": "100%",
    },
    45: {
        "Num": 45,
        "Name": "Growl",
        "Type": "Normal",
        "Category": "Status",
        "PP": 40,
        "Power": "—",
        "Accuracy": "100%",
    },
    46: {
        "Num": 46,
        "Name": "Roar",
        "Type": "Normal",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "100%",
    },
    47: {
        "Num": 47,
        "Name": "Sing",
        "Type": "Normal",
        "Category": "Status",
        "PP": 15,
        "Power": "—",
        "Accuracy": "55%",
    },
    48: {
        "Num": 48,
        "Name": "Supersonic",
        "Type": "Normal",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "55%",
    },
    49: {
        "Num": 49,
        "Name": "Sonic Boom",
        "Type": "Normal",
        "Category": "Special",
        "PP": 20,
        "Power": "—",
        "Accuracy": "90%",
    },
    50: {
        "Num": 50,
        "Name": "Disable",
        "Type": "Normal",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "55%",
    },
    51: {
        "Num": 51,
        "Name": "Acid",
        "Type": "Poison",
        "Category": "Special",
        "PP": 30,
        "Power": 40,
        "Accuracy": "100%",
    },
    52: {
        "Num": 52,
        "Name": "Ember",
        "Type": "Fire",
        "Category": "Special",
        "PP": 25,
        "Power": 40,
        "Accuracy": "100%",
    },
    53: {
        "Num": 53,
        "Name": "Flamethrower",
        "Type": "Fire",
        "Category": "Special",
        "PP": 15,
        "Power": 95,
        "Accuracy": "100%",
    },
    54: {
        "Num": 54,
        "Name": "Mist",
        "Type": "Ice",
        "Category": "Status",
        "PP": 30,
        "Power": "—",
        "Accuracy": "—",
    },
    55: {
        "Num": 55,
        "Name": "Water Gun",
        "Type": "Water",
        "Category": "Special",
        "PP": 25,
        "Power": 40,
        "Accuracy": "100%",
    },
    56: {
        "Num": 56,
        "Name": "Hydro Pump",
        "Type": "Water",
        "Category": "Special",
        "PP": 5,
        "Power": 120,
        "Accuracy": "80%",
    },
    57: {
        "Num": 57,
        "Name": "Surf",
        "Type": "Water",
        "Category": "Special",
        "PP": 15,
        "Power": 95,
        "Accuracy": "100%",
    },
    58: {
        "Num": 58,
        "Name": "Ice Beam",
        "Type": "Ice",
        "Category": "Special",
        "PP": 10,
        "Power": 95,
        "Accuracy": "100%",
    },
    59: {
        "Num": 59,
        "Name": "Blizzard",
        "Type": "Ice",
        "Category": "Special",
        "PP": 5,
        "Power": 120,
        "Accuracy": "70%",
    },
    60: {
        "Num": 60,
        "Name": "Psybeam",
        "Type": "Psychic",
        "Category": "Special",
        "PP": 20,
        "Power": 65,
        "Accuracy": "100%",
    },
    61: {
        "Num": 61,
        "Name": "Bubble Beam",
        "Type": "Water",
        "Category": "Special",
        "PP": 20,
        "Power": 65,
        "Accuracy": "100%",
    },
    62: {
        "Num": 62,
        "Name": "Aurora Beam",
        "Type": "Ice",
        "Category": "Special",
        "PP": 20,
        "Power": 65,
        "Accuracy": "100%",
    },
    63: {
        "Num": 63,
        "Name": "Hyper Beam",
        "Type": "Normal",
        "Category": "Special",
        "PP": 5,
        "Power": 150,
        "Accuracy": "90%",
    },
    64: {
        "Num": 64,
        "Name": "Peck",
        "Type": "Flying",
        "Category": "Physical",
        "PP": 35,
        "Power": 35,
        "Accuracy": "100%",
    },
    65: {
        "Num": 65,
        "Name": "Drill Peck",
        "Type": "Flying",
        "Category": "Physical",
        "PP": 20,
        "Power": 80,
        "Accuracy": "100%",
    },
    66: {
        "Num": 66,
        "Name": "Submission",
        "Type": "Fighting",
        "Category": "Physical",
        "PP": 25,
        "Power": 80,
        "Accuracy": "80%",
    },
    67: {
        "Num": 67,
        "Name": "Low Kick",
        "Type": "Fighting",
        "Category": "Physical",
        "PP": 20,
        "Power": "—",
        "Accuracy": "100%",
    },
    68: {
        "Num": 68,
        "Name": "Counter",
        "Type": "Fighting",
        "Category": "Physical",
        "PP": 20,
        "Power": "—",
        "Accuracy": "100%",
    },
    69: {
        "Num": 69,
        "Name": "Seismic Toss",
        "Type": "Fighting",
        "Category": "Physical",
        "PP": 20,
        "Power": "—",
        "Accuracy": "100%",
    },
    70: {
        "Num": 70,
        "Name": "Strength",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 15,
        "Power": 80,
        "Accuracy": "100%",
    },
    71: {
        "Num": 71,
        "Name": "Absorb",
        "Type": "Grass",
        "Category": "Special",
        "PP": 20,
        "Power": 20,
        "Accuracy": "100%",
    },
    72: {
        "Num": 72,
        "Name": "Mega Drain",
        "Type": "Grass",
        "Category": "Special",
        "PP": 10,
        "Power": 40,
        "Accuracy": "100%",
    },
    73: {
        "Num": 73,
        "Name": "Leech Seed",
        "Type": "Grass",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "90%",
    },
    74: {
        "Num": 74,
        "Name": "Growth",
        "Type": "Normal",
        "Category": "Status",
        "PP": 40,
        "Power": "—",
        "Accuracy": "—",
    },
    75: {
        "Num": 75,
        "Name": "Razor Leaf",
        "Type": "Grass",
        "Category": "Physical",
        "PP": 25,
        "Power": 55,
        "Accuracy": "95%",
    },
    76: {
        "Num": 76,
        "Name": "Solar Beam",
        "Type": "Grass",
        "Category": "Special",
        "PP": 10,
        "Power": 120,
        "Accuracy": "100%",
    },
    77: {
        "Num": 77,
        "Name": "Poison Powder",
        "Type": "Poison",
        "Category": "Status",
        "PP": 35,
        "Power": "—",
        "Accuracy": "75%",
    },
    78: {
        "Num": 78,
        "Name": "Stun Spore",
        "Type": "Grass",
        "Category": "Status",
        "PP": 30,
        "Power": "—",
        "Accuracy": "75%",
    },
    79: {
        "Num": 79,
        "Name": "Sleep Powder",
        "Type": "Grass",
        "Category": "Status",
        "PP": 15,
        "Power": "—",
        "Accuracy": "75%",
    },
    80: {
        "Num": 80,
        "Name": "Petal Dance",
        "Type": "Grass",
        "Category": "Special",
        "PP": 20,
        "Power": 70,
        "Accuracy": "100%",
    },
    81: {
        "Num": 81,
        "Name": "String Shot",
        "Type": "Bug",
        "Category": "Status",
        "PP": 40,
        "Power": "—",
        "Accuracy": "95%",
    },
    82: {
        "Num": 82,
        "Name": "Dragon Rage",
        "Type": "Dragon",
        "Category": "Special",
        "PP": 10,
        "Power": "—",
        "Accuracy": "100%",
    },
    83: {
        "Num": 83,
        "Name": "Fire Spin",
        "Type": "Fire",
        "Category": "Special",
        "PP": 15,
        "Power": 15,
        "Accuracy": "70%",
    },
    84: {
        "Num": 84,
        "Name": "Thunder Shock",
        "Type": "Electric",
        "Category": "Special",
        "PP": 30,
        "Power": 40,
        "Accuracy": "100%",
    },
    85: {
        "Num": 85,
        "Name": "Thunderbolt",
        "Type": "Electric",
        "Category": "Special",
        "PP": 15,
        "Power": 95,
        "Accuracy": "100%",
    },
    86: {
        "Num": 86,
        "Name": "Thunder Wave",
        "Type": "Electric",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "100%",
    },
    87: {
        "Num": 87,
        "Name": "Thunder",
        "Type": "Electric",
        "Category": "Special",
        "PP": 10,
        "Power": 120,
        "Accuracy": "70%",
    },
    88: {
        "Num": 88,
        "Name": "Rock Throw",
        "Type": "Rock",
        "Category": "Physical",
        "PP": 15,
        "Power": 50,
        "Accuracy": "90%",
    },
    89: {
        "Num": 89,
        "Name": "Earthquake",
        "Type": "Ground",
        "Category": "Physical",
        "PP": 10,
        "Power": 100,
        "Accuracy": "100%",
    },
    90: {
        "Num": 90,
        "Name": "Fissure",
        "Type": "Ground",
        "Category": "Physical",
        "PP": 5,
        "Power": "—",
        "Accuracy": "30%",
    },
    91: {
        "Num": 91,
        "Name": "Dig",
        "Type": "Ground",
        "Category": "Physical",
        "PP": 10,
        "Power": 60,
        "Accuracy": "100%",
    },
    92: {
        "Num": 92,
        "Name": "Toxic",
        "Type": "Poison",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "85%",
    },
    93: {
        "Num": 93,
        "Name": "Confusion",
        "Type": "Psychic",
        "Category": "Special",
        "PP": 25,
        "Power": 50,
        "Accuracy": "100%",
    },
    94: {
        "Num": 94,
        "Name": "Psychic",
        "Type": "Psychic",
        "Category": "Special",
        "PP": 10,
        "Power": 90,
        "Accuracy": "100%",
    },
    95: {
        "Num": 95,
        "Name": "Hypnosis",
        "Type": "Psychic",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "60%",
    },
    96: {
        "Num": 96,
        "Name": "Meditate",
        "Type": "Psychic",
        "Category": "Status",
        "PP": 40,
        "Power": "—",
        "Accuracy": "—",
    },
    97: {
        "Num": 97,
        "Name": "Agility",
        "Type": "Psychic",
        "Category": "Status",
        "PP": 30,
        "Power": "—",
        "Accuracy": "—",
    },
    98: {
        "Num": 98,
        "Name": "Quick Attack",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 30,
        "Power": 40,
        "Accuracy": "100%",
    },
    99: {
        "Num": 99,
        "Name": "Rage",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 20,
        "Power": 20,
        "Accuracy": "100%",
    },
    100: {
        "Num": 100,
        "Name": "Teleport",
        "Type": "Psychic",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "—",
    },
    101: {
        "Num": 101,
        "Name": "Night Shade",
        "Type": "Ghost",
        "Category": "Special",
        "PP": 15,
        "Power": "—",
        "Accuracy": "100%",
    },
    102: {
        "Num": 102,
        "Name": "Mimic",
        "Type": "Normal",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    103: {
        "Num": 103,
        "Name": "Screech",
        "Type": "Normal",
        "Category": "Status",
        "PP": 40,
        "Power": "—",
        "Accuracy": "85%",
    },
    104: {
        "Num": 104,
        "Name": "Double Team",
        "Type": "Normal",
        "Category": "Status",
        "PP": 15,
        "Power": "—",
        "Accuracy": "—",
    },
    105: {
        "Num": 105,
        "Name": "Recover",
        "Type": "Normal",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "—",
    },
    106: {
        "Num": 106,
        "Name": "Harden",
        "Type": "Normal",
        "Category": "Status",
        "PP": 30,
        "Power": "—",
        "Accuracy": "—",
    },
    107: {
        "Num": 107,
        "Name": "Minimize",
        "Type": "Normal",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "—",
    },
    108: {
        "Num": 108,
        "Name": "Smokescreen",
        "Type": "Normal",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "100%",
    },
    109: {
        "Num": 109,
        "Name": "Confuse Ray",
        "Type": "Ghost",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "100%",
    },
    110: {
        "Num": 110,
        "Name": "Withdraw",
        "Type": "Water",
        "Category": "Status",
        "PP": 40,
        "Power": "—",
        "Accuracy": "—",
    },
    111: {
        "Num": 111,
        "Name": "Defense Curl",
        "Type": "Normal",
        "Category": "Status",
        "PP": 40,
        "Power": "—",
        "Accuracy": "—",
    },
    112: {
        "Num": 112,
        "Name": "Barrier",
        "Type": "Psychic",
        "Category": "Status",
        "PP": 30,
        "Power": "—",
        "Accuracy": "—",
    },
    113: {
        "Num": 113,
        "Name": "Light Screen",
        "Type": "Psychic",
        "Category": "Status",
        "PP": 30,
        "Power": "—",
        "Accuracy": "—",
    },
    114: {
        "Num": 114,
        "Name": "Haze",
        "Type": "Ice",
        "Category": "Status",
        "PP": 30,
        "Power": "—",
        "Accuracy": "—",
    },
    115: {
        "Num": 115,
        "Name": "Reflect",
        "Type": "Psychic",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "—",
    },
    116: {
        "Num": 116,
        "Name": "Focus Energy",
        "Type": "Normal",
        "Category": "Status",
        "PP": 30,
        "Power": "—",
        "Accuracy": "—",
    },
    117: {
        "Num": 117,
        "Name": "Bide",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 10,
        "Power": "—",
        "Accuracy": "100%",
    },
    118: {
        "Num": 118,
        "Name": "Metronome",
        "Type": "Normal",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    119: {
        "Num": 119,
        "Name": "Mirror Move",
        "Type": "Flying",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "—",
    },
    120: {
        "Num": 120,
        "Name": "Self-Destruct",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 5,
        "Power": 200,
        "Accuracy": "100%",
    },
    121: {
        "Num": 121,
        "Name": "Egg Bomb",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 10,
        "Power": 100,
        "Accuracy": "75%",
    },
    122: {
        "Num": 122,
        "Name": "Lick",
        "Type": "Ghost",
        "Category": "Physical",
        "PP": 30,
        "Power": 20,
        "Accuracy": "100%",
    },
    123: {
        "Num": 123,
        "Name": "Smog",
        "Type": "Poison",
        "Category": "Special",
        "PP": 20,
        "Power": 20,
        "Accuracy": "70%",
    },
    124: {
        "Num": 124,
        "Name": "Sludge",
        "Type": "Poison",
        "Category": "Special",
        "PP": 20,
        "Power": 65,
        "Accuracy": "100%",
    },
    125: {
        "Num": 125,
        "Name": "Bone Club",
        "Type": "Ground",
        "Category": "Physical",
        "PP": 20,
        "Power": 65,
        "Accuracy": "85%",
    },
    126: {
        "Num": 126,
        "Name": "Fire Blast",
        "Type": "Fire",
        "Category": "Special",
        "PP": 5,
        "Power": 120,
        "Accuracy": "85%",
    },
    127: {
        "Num": 127,
        "Name": "Waterfall",
        "Type": "Water",
        "Category": "Physical",
        "PP": 15,
        "Power": 80,
        "Accuracy": "100%",
    },
    128: {
        "Num": 128,
        "Name": "Clamp",
        "Type": "Water",
        "Category": "Physical",
        "PP": 10,
        "Power": 35,
        "Accuracy": "75%",
    },
    129: {
        "Num": 129,
        "Name": "Swift",
        "Type": "Normal",
        "Category": "Special",
        "PP": 20,
        "Power": 60,
        "Accuracy": "—",
    },
    130: {
        "Num": 130,
        "Name": "Skull Bash",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 15,
        "Power": 100,
        "Accuracy": "100%",
    },
    131: {
        "Num": 131,
        "Name": "Spike Cannon",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 15,
        "Power": 20,
        "Accuracy": "100%",
    },
    132: {
        "Num": 132,
        "Name": "Constrict",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 35,
        "Power": 10,
        "Accuracy": "100%",
    },
    133: {
        "Num": 133,
        "Name": "Amnesia",
        "Type": "Psychic",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "—",
    },
    134: {
        "Num": 134,
        "Name": "Kinesis",
        "Type": "Psychic",
        "Category": "Status",
        "PP": 15,
        "Power": "—",
        "Accuracy": "80%",
    },
    135: {
        "Num": 135,
        "Name": "Soft-Boiled",
        "Type": "Normal",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    136: {
        "Num": 136,
        "Name": "High Jump Kick",
        "Type": "Fighting",
        "Category": "Physical",
        "PP": 20,
        "Power": 85,
        "Accuracy": "90%",
    },
    137: {
        "Num": 137,
        "Name": "Glare",
        "Type": "Normal",
        "Category": "Status",
        "PP": 30,
        "Power": "—",
        "Accuracy": "75%",
    },
    138: {
        "Num": 138,
        "Name": "Dream Eater",
        "Type": "Psychic",
        "Category": "Special",
        "PP": 15,
        "Power": 100,
        "Accuracy": "100%",
    },
    139: {
        "Num": 139,
        "Name": "Poison Gas",
        "Type": "Poison",
        "Category": "Status",
        "PP": 40,
        "Power": "—",
        "Accuracy": "55%",
    },
    140: {
        "Num": 140,
        "Name": "Barrage",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 20,
        "Power": 15,
        "Accuracy": "85%",
    },
    141: {
        "Num": 141,
        "Name": "Leech Life",
        "Type": "Bug",
        "Category": "Physical",
        "PP": 15,
        "Power": 20,
        "Accuracy": "100%",
    },
    142: {
        "Num": 142,
        "Name": "Lovely Kiss",
        "Type": "Normal",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "75%",
    },
    143: {
        "Num": 143,
        "Name": "Sky Attack",
        "Type": "Flying",
        "Category": "Physical",
        "PP": 5,
        "Power": 140,
        "Accuracy": "90%",
    },
    144: {
        "Num": 144,
        "Name": "Transform",
        "Type": "Normal",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    145: {
        "Num": 145,
        "Name": "Bubble",
        "Type": "Water",
        "Category": "Special",
        "PP": 30,
        "Power": 20,
        "Accuracy": "100%",
    },
    146: {
        "Num": 146,
        "Name": "Dizzy Punch",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 10,
        "Power": 70,
        "Accuracy": "100%",
    },
    147: {
        "Num": 147,
        "Name": "Spore",
        "Type": "Grass",
        "Category": "Status",
        "PP": 15,
        "Power": "—",
        "Accuracy": "100%",
    },
    148: {
        "Num": 148,
        "Name": "Flash",
        "Type": "Normal",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "70%",
    },
    149: {
        "Num": 149,
        "Name": "Psywave",
        "Type": "Psychic",
        "Category": "Special",
        "PP": 15,
        "Power": "—",
        "Accuracy": "80%",
    },
    150: {
        "Num": 150,
        "Name": "Splash",
        "Type": "Normal",
        "Category": "Status",
        "PP": 40,
        "Power": "—",
        "Accuracy": "—",
    },
    151: {
        "Num": 151,
        "Name": "Acid Armor",
        "Type": "Poison",
        "Category": "Status",
        "PP": 40,
        "Power": "—",
        "Accuracy": "—",
    },
    152: {
        "Num": 152,
        "Name": "Crabhammer",
        "Type": "Water",
        "Category": "Physical",
        "PP": 10,
        "Power": 90,
        "Accuracy": "85%",
    },
    153: {
        "Num": 153,
        "Name": "Explosion",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 5,
        "Power": 250,
        "Accuracy": "100%",
    },
    154: {
        "Num": 154,
        "Name": "Fury Swipes",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 15,
        "Power": 18,
        "Accuracy": "80%",
    },
    155: {
        "Num": 155,
        "Name": "Bonemerang",
        "Type": "Ground",
        "Category": "Physical",
        "PP": 10,
        "Power": 50,
        "Accuracy": "90%",
    },
    156: {
        "Num": 156,
        "Name": "Rest",
        "Type": "Psychic",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    157: {
        "Num": 157,
        "Name": "Rock Slide",
        "Type": "Rock",
        "Category": "Physical",
        "PP": 10,
        "Power": 75,
        "Accuracy": "90%",
    },
    158: {
        "Num": 158,
        "Name": "Hyper Fang",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 15,
        "Power": 80,
        "Accuracy": "90%",
    },
    159: {
        "Num": 159,
        "Name": "Sharpen",
        "Type": "Normal",
        "Category": "Status",
        "PP": 30,
        "Power": "—",
        "Accuracy": "—",
    },
    160: {
        "Num": 160,
        "Name": "Conversion",
        "Type": "Normal",
        "Category": "Status",
        "PP": 30,
        "Power": "—",
        "Accuracy": "—",
    },
    161: {
        "Num": 161,
        "Name": "Tri Attack",
        "Type": "Normal",
        "Category": "Special",
        "PP": 10,
        "Power": 80,
        "Accuracy": "100%",
    },
    162: {
        "Num": 162,
        "Name": "Super Fang",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 10,
        "Power": "—",
        "Accuracy": "90%",
    },
    163: {
        "Num": 163,
        "Name": "Slash",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 20,
        "Power": 70,
        "Accuracy": "100%",
    },
    164: {
        "Num": 164,
        "Name": "Substitute",
        "Type": "Normal",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    165: {
        "Num": 165,
        "Name": "Struggle",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 10,
        "Power": 50,
        "Accuracy": "100%",
    },
    166: {
        "Num": 166,
        "Name": "Sketch",
        "Type": "Normal",
        "Category": "Status",
        "PP": 1,
        "Power": "—",
        "Accuracy": "—",
    },
    167: {
        "Num": 167,
        "Name": "Triple Kick",
        "Type": "Fighting",
        "Category": "Physical",
        "PP": 10,
        "Power": 10,
        "Accuracy": "90%",
    },
    168: {
        "Num": 168,
        "Name": "Thief",
        "Type": "Dark",
        "Category": "Physical",
        "PP": 10,
        "Power": 40,
        "Accuracy": "100%",
    },
    169: {
        "Num": 169,
        "Name": "Spider Web",
        "Type": "Bug",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    170: {
        "Num": 170,
        "Name": "Mind Reader",
        "Type": "Normal",
        "Category": "Status",
        "PP": 5,
        "Power": "—",
        "Accuracy": "100%",
    },
    171: {
        "Num": 171,
        "Name": "Nightmare",
        "Type": "Ghost",
        "Category": "Status",
        "PP": 15,
        "Power": "—",
        "Accuracy": "100%",
    },
    172: {
        "Num": 172,
        "Name": "Flame Wheel",
        "Type": "Fire",
        "Category": "Physical",
        "PP": 25,
        "Power": 60,
        "Accuracy": "100%",
    },
    173: {
        "Num": 173,
        "Name": "Snore",
        "Type": "Normal",
        "Category": "Special",
        "PP": 15,
        "Power": 40,
        "Accuracy": "100%",
    },
    174: {
        "Num": 174,
        "Name": "Curse",
        "Type": "Ghost",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    175: {
        "Num": 175,
        "Name": "Flail",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 15,
        "Power": "—",
        "Accuracy": "100%",
    },
    176: {
        "Num": 176,
        "Name": "Conversion 2",
        "Type": "Normal",
        "Category": "Status",
        "PP": 30,
        "Power": "—",
        "Accuracy": "—",
    },
    177: {
        "Num": 177,
        "Name": "Aeroblast",
        "Type": "Flying",
        "Category": "Special",
        "PP": 5,
        "Power": 100,
        "Accuracy": "95%",
    },
    178: {
        "Num": 178,
        "Name": "Cotton Spore",
        "Type": "Grass",
        "Category": "Status",
        "PP": 40,
        "Power": "—",
        "Accuracy": "85%",
    },
    179: {
        "Num": 179,
        "Name": "Reversal",
        "Type": "Fighting",
        "Category": "Physical",
        "PP": 15,
        "Power": "—",
        "Accuracy": "100%",
    },
    180: {
        "Num": 180,
        "Name": "Spite",
        "Type": "Ghost",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "100%",
    },
    181: {
        "Num": 181,
        "Name": "Powder Snow",
        "Type": "Ice",
        "Category": "Special",
        "PP": 25,
        "Power": 40,
        "Accuracy": "100%",
    },
    182: {
        "Num": 182,
        "Name": "Protect",
        "Type": "Normal",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    183: {
        "Num": 183,
        "Name": "Mach Punch",
        "Type": "Fighting",
        "Category": "Physical",
        "PP": 30,
        "Power": 40,
        "Accuracy": "100%",
    },
    184: {
        "Num": 184,
        "Name": "Scary Face",
        "Type": "Normal",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "90%",
    },
    185: {
        "Num": 185,
        "Name": "Feint Attack",
        "Type": "Dark",
        "Category": "Physical",
        "PP": 20,
        "Power": 60,
        "Accuracy": "—",
    },
    186: {
        "Num": 186,
        "Name": "Sweet Kiss",
        "Type": "Normal",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "75%",
    },
    187: {
        "Num": 187,
        "Name": "Belly Drum",
        "Type": "Normal",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    188: {
        "Num": 188,
        "Name": "Sludge Bomb",
        "Type": "Poison",
        "Category": "Special",
        "PP": 10,
        "Power": 90,
        "Accuracy": "100%",
    },
    189: {
        "Num": 189,
        "Name": "Mud-Slap",
        "Type": "Ground",
        "Category": "Special",
        "PP": 10,
        "Power": 20,
        "Accuracy": "100%",
    },
    190: {
        "Num": 190,
        "Name": "Octazooka",
        "Type": "Water",
        "Category": "Special",
        "PP": 10,
        "Power": 65,
        "Accuracy": "85%",
    },
    191: {
        "Num": 191,
        "Name": "Spikes",
        "Type": "Ground",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "—",
    },
    192: {
        "Num": 192,
        "Name": "Zap Cannon",
        "Type": "Electric",
        "Category": "Special",
        "PP": 5,
        "Power": 100,
        "Accuracy": "50%",
    },
    193: {
        "Num": 193,
        "Name": "Foresight",
        "Type": "Normal",
        "Category": "Status",
        "PP": 40,
        "Power": "—",
        "Accuracy": "100%",
    },
    194: {
        "Num": 194,
        "Name": "Destiny Bond",
        "Type": "Ghost",
        "Category": "Status",
        "PP": 5,
        "Power": "—",
        "Accuracy": "—",
    },
    195: {
        "Num": 195,
        "Name": "Perish Song",
        "Type": "Normal",
        "Category": "Status",
        "PP": 5,
        "Power": "—",
        "Accuracy": "—",
    },
    196: {
        "Num": 196,
        "Name": "Icy Wind",
        "Type": "Ice",
        "Category": "Special",
        "PP": 15,
        "Power": 55,
        "Accuracy": "95%",
    },
    197: {
        "Num": 197,
        "Name": "Detect",
        "Type": "Fighting",
        "Category": "Status",
        "PP": 5,
        "Power": "—",
        "Accuracy": "—",
    },
    198: {
        "Num": 198,
        "Name": "Bone Rush",
        "Type": "Ground",
        "Category": "Physical",
        "PP": 10,
        "Power": 25,
        "Accuracy": "80%",
    },
    199: {
        "Num": 199,
        "Name": "Lock-On",
        "Type": "Normal",
        "Category": "Status",
        "PP": 5,
        "Power": "—",
        "Accuracy": "100%",
    },
    200: {
        "Num": 200,
        "Name": "Outrage",
        "Type": "Dragon",
        "Category": "Physical",
        "PP": 15,
        "Power": 90,
        "Accuracy": "100%",
    },
    201: {
        "Num": 201,
        "Name": "Sandstorm",
        "Type": "Rock",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    202: {
        "Num": 202,
        "Name": "Giga Drain",
        "Type": "Grass",
        "Category": "Special",
        "PP": 5,
        "Power": 60,
        "Accuracy": "100%",
    },
    203: {
        "Num": 203,
        "Name": "Endure",
        "Type": "Normal",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    204: {
        "Num": 204,
        "Name": "Charm",
        "Type": "Normal",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "100%",
    },
    205: {
        "Num": 205,
        "Name": "Rollout",
        "Type": "Rock",
        "Category": "Physical",
        "PP": 20,
        "Power": 30,
        "Accuracy": "90%",
    },
    206: {
        "Num": 206,
        "Name": "False Swipe",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 40,
        "Power": 40,
        "Accuracy": "100%",
    },
    207: {
        "Num": 207,
        "Name": "Swagger",
        "Type": "Normal",
        "Category": "Status",
        "PP": 15,
        "Power": "—",
        "Accuracy": "90%",
    },
    208: {
        "Num": 208,
        "Name": "Milk Drink",
        "Type": "Normal",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    209: {
        "Num": 209,
        "Name": "Spark",
        "Type": "Electric",
        "Category": "Physical",
        "PP": 20,
        "Power": 65,
        "Accuracy": "100%",
    },
    210: {
        "Num": 210,
        "Name": "Fury Cutter",
        "Type": "Bug",
        "Category": "Physical",
        "PP": 20,
        "Power": 10,
        "Accuracy": "95%",
    },
    211: {
        "Num": 211,
        "Name": "Steel Wing",
        "Type": "Steel",
        "Category": "Physical",
        "PP": 25,
        "Power": 70,
        "Accuracy": "90%",
    },
    212: {
        "Num": 212,
        "Name": "Mean Look",
        "Type": "Normal",
        "Category": "Status",
        "PP": 5,
        "Power": "—",
        "Accuracy": "—",
    },
    213: {
        "Num": 213,
        "Name": "Attract",
        "Type": "Normal",
        "Category": "Status",
        "PP": 15,
        "Power": "—",
        "Accuracy": "100%",
    },
    214: {
        "Num": 214,
        "Name": "Sleep Talk",
        "Type": "Normal",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    215: {
        "Num": 215,
        "Name": "Heal Bell",
        "Type": "Normal",
        "Category": "Status",
        "PP": 5,
        "Power": "—",
        "Accuracy": "—",
    },
    216: {
        "Num": 216,
        "Name": "Return",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 20,
        "Power": "—",
        "Accuracy": "100%",
    },
    217: {
        "Num": 217,
        "Name": "Present",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 15,
        "Power": "—",
        "Accuracy": "90%",
    },
    218: {
        "Num": 218,
        "Name": "Frustration",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 20,
        "Power": "—",
        "Accuracy": "100%",
    },
    219: {
        "Num": 219,
        "Name": "Safeguard",
        "Type": "Normal",
        "Category": "Status",
        "PP": 25,
        "Power": "—",
        "Accuracy": "—",
    },
    220: {
        "Num": 220,
        "Name": "Pain Split",
        "Type": "Normal",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "—",
    },
    221: {
        "Num": 221,
        "Name": "Sacred Fire",
        "Type": "Fire",
        "Category": "Physical",
        "PP": 5,
        "Power": 100,
        "Accuracy": "95%",
    },
    222: {
        "Num": 222,
        "Name": "Magnitude",
        "Type": "Ground",
        "Category": "Physical",
        "PP": 30,
        "Power": "—",
        "Accuracy": "100%",
    },
    223: {
        "Num": 223,
        "Name": "Dynamic Punch",
        "Type": "Fighting",
        "Category": "Physical",
        "PP": 5,
        "Power": 100,
        "Accuracy": "50%",
    },
    224: {
        "Num": 224,
        "Name": "Megahorn",
        "Type": "Bug",
        "Category": "Physical",
        "PP": 10,
        "Power": 120,
        "Accuracy": "85%",
    },
    225: {
        "Num": 225,
        "Name": "Dragon Breath",
        "Type": "Dragon",
        "Category": "Special",
        "PP": 20,
        "Power": 60,
        "Accuracy": "100%",
    },
    226: {
        "Num": 226,
        "Name": "Baton Pass",
        "Type": "Normal",
        "Category": "Status",
        "PP": 40,
        "Power": "—",
        "Accuracy": "—",
    },
    227: {
        "Num": 227,
        "Name": "Encore",
        "Type": "Normal",
        "Category": "Status",
        "PP": 5,
        "Power": "—",
        "Accuracy": "100%",
    },
    228: {
        "Num": 228,
        "Name": "Pursuit",
        "Type": "Dark",
        "Category": "Physical",
        "PP": 20,
        "Power": 40,
        "Accuracy": "100%",
    },
    229: {
        "Num": 229,
        "Name": "Rapid Spin",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 40,
        "Power": 20,
        "Accuracy": "100%",
    },
    230: {
        "Num": 230,
        "Name": "Sweet Scent",
        "Type": "Normal",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "100%",
    },
    231: {
        "Num": 231,
        "Name": "Iron Tail",
        "Type": "Steel",
        "Category": "Physical",
        "PP": 15,
        "Power": 100,
        "Accuracy": "75%",
    },
    232: {
        "Num": 232,
        "Name": "Metal Claw",
        "Type": "Steel",
        "Category": "Physical",
        "PP": 35,
        "Power": 50,
        "Accuracy": "95%",
    },
    233: {
        "Num": 233,
        "Name": "Vital Throw",
        "Type": "Fighting",
        "Category": "Physical",
        "PP": 10,
        "Power": 70,
        "Accuracy": "—",
    },
    234: {
        "Num": 234,
        "Name": "Morning Sun",
        "Type": "Normal",
        "Category": "Status",
        "PP": 5,
        "Power": "—",
        "Accuracy": "—",
    },
    235: {
        "Num": 235,
        "Name": "Synthesis",
        "Type": "Grass",
        "Category": "Status",
        "PP": 5,
        "Power": "—",
        "Accuracy": "—",
    },
    236: {
        "Num": 236,
        "Name": "Moonlight",
        "Type": "Normal",
        "Category": "Status",
        "PP": 5,
        "Power": "—",
        "Accuracy": "—",
    },
    237: {
        "Num": 237,
        "Name": "Hidden Power",
        "Type": "Normal",
        "Category": "Special",
        "PP": 15,
        "Power": "—",
        "Accuracy": "100%",
    },
    238: {
        "Num": 238,
        "Name": "Cross Chop",
        "Type": "Fighting",
        "Category": "Physical",
        "PP": 5,
        "Power": 100,
        "Accuracy": "80%",
    },
    239: {
        "Num": 239,
        "Name": "Twister",
        "Type": "Dragon",
        "Category": "Special",
        "PP": 20,
        "Power": 40,
        "Accuracy": "100%",
    },
    240: {
        "Num": 240,
        "Name": "Rain Dance",
        "Type": "Water",
        "Category": "Status",
        "PP": 5,
        "Power": "—",
        "Accuracy": "—",
    },
    241: {
        "Num": 241,
        "Name": "Sunny Day",
        "Type": "Fire",
        "Category": "Status",
        "PP": 5,
        "Power": "—",
        "Accuracy": "—",
    },
    242: {
        "Num": 242,
        "Name": "Crunch",
        "Type": "Dark",
        "Category": "Physical",
        "PP": 15,
        "Power": 80,
        "Accuracy": "100%",
    },
    243: {
        "Num": 243,
        "Name": "Mirror Coat",
        "Type": "Psychic",
        "Category": "Special",
        "PP": 20,
        "Power": "—",
        "Accuracy": "100%",
    },
    244: {
        "Num": 244,
        "Name": "Psych Up",
        "Type": "Normal",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    245: {
        "Num": 245,
        "Name": "Extreme Speed",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 5,
        "Power": 80,
        "Accuracy": "100%",
    },
    246: {
        "Num": 246,
        "Name": "Ancient Power",
        "Type": "Rock",
        "Category": "Special",
        "PP": 5,
        "Power": 60,
        "Accuracy": "100%",
    },
    247: {
        "Num": 247,
        "Name": "Shadow Ball",
        "Type": "Ghost",
        "Category": "Special",
        "PP": 15,
        "Power": 80,
        "Accuracy": "100%",
    },
    248: {
        "Num": 248,
        "Name": "Future Sight",
        "Type": "Psychic",
        "Category": "Special",
        "PP": 15,
        "Power": 80,
        "Accuracy": "90%",
    },
    249: {
        "Num": 249,
        "Name": "Rock Smash",
        "Type": "Fighting",
        "Category": "Physical",
        "PP": 15,
        "Power": 20,
        "Accuracy": "100%",
    },
    250: {
        "Num": 250,
        "Name": "Whirlpool",
        "Type": "Water",
        "Category": "Special",
        "PP": 15,
        "Power": 15,
        "Accuracy": "70%",
    },
    251: {
        "Num": 251,
        "Name": "Beat Up",
        "Type": "Dark",
        "Category": "Physical",
        "PP": 10,
        "Power": 10,
        "Accuracy": "100%",
    },
    252: {
        "Num": 252,
        "Name": "Fake Out",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 10,
        "Power": 40,
        "Accuracy": "100%",
    },
    253: {
        "Num": 253,
        "Name": "Uproar",
        "Type": "Normal",
        "Category": "Special",
        "PP": 10,
        "Power": 50,
        "Accuracy": "100%",
    },
    254: {
        "Num": 254,
        "Name": "Stockpile",
        "Type": "Normal",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    255: {
        "Num": 255,
        "Name": "Spit Up",
        "Type": "Normal",
        "Category": "Special",
        "PP": 10,
        "Power": "—",
        "Accuracy": "100%",
    },
    256: {
        "Num": 256,
        "Name": "Swallow",
        "Type": "Normal",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    257: {
        "Num": 257,
        "Name": "Heat Wave",
        "Type": "Fire",
        "Category": "Special",
        "PP": 10,
        "Power": 100,
        "Accuracy": "90%",
    },
    258: {
        "Num": 258,
        "Name": "Hail",
        "Type": "Ice",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    259: {
        "Num": 259,
        "Name": "Torment",
        "Type": "Dark",
        "Category": "Status",
        "PP": 15,
        "Power": "—",
        "Accuracy": "100%",
    },
    260: {
        "Num": 260,
        "Name": "Flatter",
        "Type": "Dark",
        "Category": "Status",
        "PP": 15,
        "Power": "—",
        "Accuracy": "100%",
    },
    261: {
        "Num": 261,
        "Name": "Will-O-Wisp",
        "Type": "Fire",
        "Category": "Status",
        "PP": 15,
        "Power": "—",
        "Accuracy": "75%",
    },
    262: {
        "Num": 262,
        "Name": "Memento",
        "Type": "Dark",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "100%",
    },
    263: {
        "Num": 263,
        "Name": "Facade",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 20,
        "Power": 70,
        "Accuracy": "100%",
    },
    264: {
        "Num": 264,
        "Name": "Focus Punch",
        "Type": "Fighting",
        "Category": "Physical",
        "PP": 20,
        "Power": 150,
        "Accuracy": "100%",
    },
    265: {
        "Num": 265,
        "Name": "Smelling Salts",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 10,
        "Power": 60,
        "Accuracy": "100%",
    },
    266: {
        "Num": 266,
        "Name": "Follow Me",
        "Type": "Normal",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "—",
    },
    267: {
        "Num": 267,
        "Name": "Nature Power",
        "Type": "Normal",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "—",
    },
    268: {
        "Num": 268,
        "Name": "Charge",
        "Type": "Electric",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "—",
    },
    269: {
        "Num": 269,
        "Name": "Taunt",
        "Type": "Dark",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "100%",
    },
    270: {
        "Num": 270,
        "Name": "Helping Hand",
        "Type": "Normal",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "—",
    },
    271: {
        "Num": 271,
        "Name": "Trick",
        "Type": "Psychic",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "100%",
    },
    272: {
        "Num": 272,
        "Name": "Role Play",
        "Type": "Psychic",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    273: {
        "Num": 273,
        "Name": "Wish",
        "Type": "Normal",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    274: {
        "Num": 274,
        "Name": "Assist",
        "Type": "Normal",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "—",
    },
    275: {
        "Num": 275,
        "Name": "Ingrain",
        "Type": "Grass",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "—",
    },
    276: {
        "Num": 276,
        "Name": "Superpower",
        "Type": "Fighting",
        "Category": "Physical",
        "PP": 5,
        "Power": 120,
        "Accuracy": "100%",
    },
    277: {
        "Num": 277,
        "Name": "Magic Coat",
        "Type": "Psychic",
        "Category": "Status",
        "PP": 15,
        "Power": "—",
        "Accuracy": "—",
    },
    278: {
        "Num": 278,
        "Name": "Recycle",
        "Type": "Normal",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    279: {
        "Num": 279,
        "Name": "Revenge",
        "Type": "Fighting",
        "Category": "Physical",
        "PP": 10,
        "Power": 60,
        "Accuracy": "100%",
    },
    280: {
        "Num": 280,
        "Name": "Brick Break",
        "Type": "Fighting",
        "Category": "Physical",
        "PP": 15,
        "Power": 75,
        "Accuracy": "100%",
    },
    281: {
        "Num": 281,
        "Name": "Yawn",
        "Type": "Normal",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    282: {
        "Num": 282,
        "Name": "Knock Off",
        "Type": "Dark",
        "Category": "Physical",
        "PP": 20,
        "Power": 20,
        "Accuracy": "100%",
    },
    283: {
        "Num": 283,
        "Name": "Endeavor",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 5,
        "Power": "—",
        "Accuracy": "100%",
    },
    284: {
        "Num": 284,
        "Name": "Eruption",
        "Type": "Fire",
        "Category": "Special",
        "PP": 5,
        "Power": 150,
        "Accuracy": "100%",
    },
    285: {
        "Num": 285,
        "Name": "Skill Swap",
        "Type": "Psychic",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    286: {
        "Num": 286,
        "Name": "Imprison",
        "Type": "Psychic",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    287: {
        "Num": 287,
        "Name": "Refresh",
        "Type": "Normal",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "—",
    },
    288: {
        "Num": 288,
        "Name": "Grudge",
        "Type": "Ghost",
        "Category": "Status",
        "PP": 5,
        "Power": "—",
        "Accuracy": "—",
    },
    289: {
        "Num": 289,
        "Name": "Snatch",
        "Type": "Dark",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    290: {
        "Num": 290,
        "Name": "Secret Power",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 20,
        "Power": 70,
        "Accuracy": "100%",
    },
    291: {
        "Num": 291,
        "Name": "Dive",
        "Type": "Water",
        "Category": "Physical",
        "PP": 10,
        "Power": 60,
        "Accuracy": "100%",
    },
    292: {
        "Num": 292,
        "Name": "Arm Thrust",
        "Type": "Fighting",
        "Category": "Physical",
        "PP": 20,
        "Power": 15,
        "Accuracy": "100%",
    },
    293: {
        "Num": 293,
        "Name": "Camouflage",
        "Type": "Normal",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "—",
    },
    294: {
        "Num": 294,
        "Name": "Tail Glow",
        "Type": "Bug",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "—",
    },
    295: {
        "Num": 295,
        "Name": "Luster Purge",
        "Type": "Psychic",
        "Category": "Special",
        "PP": 5,
        "Power": 70,
        "Accuracy": "100%",
    },
    296: {
        "Num": 296,
        "Name": "Mist Ball",
        "Type": "Psychic",
        "Category": "Special",
        "PP": 5,
        "Power": 70,
        "Accuracy": "100%",
    },
    297: {
        "Num": 297,
        "Name": "Feather Dance",
        "Type": "Flying",
        "Category": "Status",
        "PP": 15,
        "Power": "—",
        "Accuracy": "100%",
    },
    298: {
        "Num": 298,
        "Name": "Teeter Dance",
        "Type": "Normal",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "100%",
    },
    299: {
        "Num": 299,
        "Name": "Blaze Kick",
        "Type": "Fire",
        "Category": "Physical",
        "PP": 10,
        "Power": 85,
        "Accuracy": "90%",
    },
    300: {
        "Num": 300,
        "Name": "Mud Sport",
        "Type": "Ground",
        "Category": "Status",
        "PP": 15,
        "Power": "—",
        "Accuracy": "—",
    },
    301: {
        "Num": 301,
        "Name": "Ice Ball",
        "Type": "Ice",
        "Category": "Physical",
        "PP": 20,
        "Power": 30,
        "Accuracy": "90%",
    },
    302: {
        "Num": 302,
        "Name": "Needle Arm",
        "Type": "Grass",
        "Category": "Physical",
        "PP": 15,
        "Power": 60,
        "Accuracy": "100%",
    },
    303: {
        "Num": 303,
        "Name": "Slack Off",
        "Type": "Normal",
        "Category": "Status",
        "PP": 10,
        "Power": "—",
        "Accuracy": "—",
    },
    304: {
        "Num": 304,
        "Name": "Hyper Voice",
        "Type": "Normal",
        "Category": "Special",
        "PP": 10,
        "Power": 90,
        "Accuracy": "100%",
    },
    305: {
        "Num": 305,
        "Name": "Poison Fang",
        "Type": "Poison",
        "Category": "Physical",
        "PP": 15,
        "Power": 50,
        "Accuracy": "100%",
    },
    306: {
        "Num": 306,
        "Name": "Crush Claw",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 10,
        "Power": 75,
        "Accuracy": "95%",
    },
    307: {
        "Num": 307,
        "Name": "Blast Burn",
        "Type": "Fire",
        "Category": "Special",
        "PP": 5,
        "Power": 150,
        "Accuracy": "90%",
    },
    308: {
        "Num": 308,
        "Name": "Hydro Cannon",
        "Type": "Water",
        "Category": "Special",
        "PP": 5,
        "Power": 150,
        "Accuracy": "90%",
    },
    309: {
        "Num": 309,
        "Name": "Meteor Mash",
        "Type": "Steel",
        "Category": "Physical",
        "PP": 10,
        "Power": 100,
        "Accuracy": "85%",
    },
    310: {
        "Num": 310,
        "Name": "Astonish",
        "Type": "Ghost",
        "Category": "Physical",
        "PP": 15,
        "Power": 30,
        "Accuracy": "100%",
    },
    311: {
        "Num": 311,
        "Name": "Weather Ball",
        "Type": "Normal",
        "Category": "Special",
        "PP": 10,
        "Power": 50,
        "Accuracy": "100%",
    },
    312: {
        "Num": 312,
        "Name": "Aromatherapy",
        "Type": "Grass",
        "Category": "Status",
        "PP": 5,
        "Power": "—",
        "Accuracy": "—",
    },
    313: {
        "Num": 313,
        "Name": "Fake Tears",
        "Type": "Dark",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "100%",
    },
    314: {
        "Num": 314,
        "Name": "Air Cutter",
        "Type": "Flying",
        "Category": "Special",
        "PP": 25,
        "Power": 55,
        "Accuracy": "95%",
    },
    315: {
        "Num": 315,
        "Name": "Overheat",
        "Type": "Fire",
        "Category": "Special",
        "PP": 5,
        "Power": 140,
        "Accuracy": "90%",
    },
    316: {
        "Num": 316,
        "Name": "Odor Sleuth",
        "Type": "Normal",
        "Category": "Status",
        "PP": 40,
        "Power": "—",
        "Accuracy": "100%",
    },
    317: {
        "Num": 317,
        "Name": "Rock Tomb",
        "Type": "Rock",
        "Category": "Physical",
        "PP": 10,
        "Power": 50,
        "Accuracy": "80%",
    },
    318: {
        "Num": 318,
        "Name": "Silver Wind",
        "Type": "Bug",
        "Category": "Special",
        "PP": 5,
        "Power": 60,
        "Accuracy": "100%",
    },
    319: {
        "Num": 319,
        "Name": "Metal Sound",
        "Type": "Steel",
        "Category": "Status",
        "PP": 40,
        "Power": "—",
        "Accuracy": "85%",
    },
    320: {
        "Num": 320,
        "Name": "Grass Whistle",
        "Type": "Grass",
        "Category": "Status",
        "PP": 15,
        "Power": "—",
        "Accuracy": "55%",
    },
    321: {
        "Num": 321,
        "Name": "Tickle",
        "Type": "Normal",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "100%",
    },
    322: {
        "Num": 322,
        "Name": "Cosmic Power",
        "Type": "Psychic",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "—",
    },
    323: {
        "Num": 323,
        "Name": "Water Spout",
        "Type": "Water",
        "Category": "Special",
        "PP": 5,
        "Power": 150,
        "Accuracy": "100%",
    },
    324: {
        "Num": 324,
        "Name": "Signal Beam",
        "Type": "Bug",
        "Category": "Special",
        "PP": 15,
        "Power": 75,
        "Accuracy": "100%",
    },
    325: {
        "Num": 325,
        "Name": "Shadow Punch",
        "Type": "Ghost",
        "Category": "Physical",
        "PP": 20,
        "Power": 60,
        "Accuracy": "—",
    },
    326: {
        "Num": 326,
        "Name": "Extrasensory",
        "Type": "Psychic",
        "Category": "Special",
        "PP": 30,
        "Power": 80,
        "Accuracy": "100%",
    },
    327: {
        "Num": 327,
        "Name": "Sky Uppercut",
        "Type": "Fighting",
        "Category": "Physical",
        "PP": 15,
        "Power": 85,
        "Accuracy": "90%",
    },
    328: {
        "Num": 328,
        "Name": "Sand Tomb",
        "Type": "Ground",
        "Category": "Physical",
        "PP": 15,
        "Power": 15,
        "Accuracy": "70%",
    },
    329: {
        "Num": 329,
        "Name": "Sheer Cold",
        "Type": "Ice",
        "Category": "Special",
        "PP": 5,
        "Power": "—",
        "Accuracy": "30%",
    },
    330: {
        "Num": 330,
        "Name": "Muddy Water",
        "Type": "Water",
        "Category": "Special",
        "PP": 10,
        "Power": 95,
        "Accuracy": "85%",
    },
    331: {
        "Num": 331,
        "Name": "Bullet Seed",
        "Type": "Grass",
        "Category": "Physical",
        "PP": 30,
        "Power": 10,
        "Accuracy": "100%",
    },
    332: {
        "Num": 332,
        "Name": "Aerial Ace",
        "Type": "Flying",
        "Category": "Physical",
        "PP": 20,
        "Power": 60,
        "Accuracy": "—",
    },
    333: {
        "Num": 333,
        "Name": "Icicle Spear",
        "Type": "Ice",
        "Category": "Physical",
        "PP": 30,
        "Power": 10,
        "Accuracy": "100%",
    },
    334: {
        "Num": 334,
        "Name": "Iron Defense",
        "Type": "Steel",
        "Category": "Status",
        "PP": 15,
        "Power": "—",
        "Accuracy": "—",
    },
    335: {
        "Num": 335,
        "Name": "Block",
        "Type": "Normal",
        "Category": "Status",
        "PP": 5,
        "Power": "—",
        "Accuracy": "—",
    },
    336: {
        "Num": 336,
        "Name": "Howl",
        "Type": "Normal",
        "Category": "Status",
        "PP": 40,
        "Power": "—",
        "Accuracy": "—",
    },
    337: {
        "Num": 337,
        "Name": "Dragon Claw",
        "Type": "Dragon",
        "Category": "Physical",
        "PP": 15,
        "Power": 80,
        "Accuracy": "100%",
    },
    338: {
        "Num": 338,
        "Name": "Frenzy Plant",
        "Type": "Grass",
        "Category": "Special",
        "PP": 5,
        "Power": 150,
        "Accuracy": "90%",
    },
    339: {
        "Num": 339,
        "Name": "Bulk Up",
        "Type": "Fighting",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "—",
    },
    340: {
        "Num": 340,
        "Name": "Bounce",
        "Type": "Flying",
        "Category": "Physical",
        "PP": 5,
        "Power": 85,
        "Accuracy": "85%",
    },
    341: {
        "Num": 341,
        "Name": "Mud Shot",
        "Type": "Ground",
        "Category": "Special",
        "PP": 15,
        "Power": 55,
        "Accuracy": "95%",
    },
    342: {
        "Num": 342,
        "Name": "Poison Tail",
        "Type": "Poison",
        "Category": "Physical",
        "PP": 25,
        "Power": 50,
        "Accuracy": "100%",
    },
    343: {
        "Num": 343,
        "Name": "Covet",
        "Type": "Normal",
        "Category": "Physical",
        "PP": 40,
        "Power": 40,
        "Accuracy": "100%",
    },
    344: {
        "Num": 344,
        "Name": "Volt Tackle",
        "Type": "Electric",
        "Category": "Physical",
        "PP": 15,
        "Power": 120,
        "Accuracy": "100%",
    },
    345: {
        "Num": 345,
        "Name": "Magical Leaf",
        "Type": "Grass",
        "Category": "Special",
        "PP": 20,
        "Power": 60,
        "Accuracy": "—",
    },
    346: {
        "Num": 346,
        "Name": "Water Sport",
        "Type": "Water",
        "Category": "Status",
        "PP": 15,
        "Power": "—",
        "Accuracy": "—",
    },
    347: {
        "Num": 347,
        "Name": "Calm Mind",
        "Type": "Psychic",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "—",
    },
    348: {
        "Num": 348,
        "Name": "Leaf Blade",
        "Type": "Grass",
        "Category": "Physical",
        "PP": 15,
        "Power": 70,
        "Accuracy": "100%",
    },
    349: {
        "Num": 349,
        "Name": "Dragon Dance",
        "Type": "Dragon",
        "Category": "Status",
        "PP": 20,
        "Power": "—",
        "Accuracy": "—",
    },
    350: {
        "Num": 350,
        "Name": "Rock Blast",
        "Type": "Rock",
        "Category": "Physical",
        "PP": 10,
        "Power": 25,
        "Accuracy": "80%",
    },
    351: {
        "Num": 351,
        "Name": "Shock Wave",
        "Type": "Electric",
        "Category": "Special",
        "PP": 20,
        "Power": 60,
        "Accuracy": "—",
    },
    352: {
        "Num": 352,
        "Name": "Water Pulse",
        "Type": "Water",
        "Category": "Special",
        "PP": 20,
        "Power": 60,
        "Accuracy": "100%",
    },
    353: {
        "Num": 353,
        "Name": "Doom Desire",
        "Type": "Steel",
        "Category": "Special",
        "PP": 5,
        "Power": 120,
        "Accuracy": "85%",
    },
    354: {
        "Num": 354,
        "Name": "Psycho Boost",
        "Type": "Psychic",
        "Category": "Special",
        "PP": 5,
        "Power": 140,
        "Accuracy": "90%",
    },
}
